# Our own welcome image instead of ST's logo (issue #59).
#
# U-Boot shows this picture as the boot menu's background (extlinux
# "MENU BACKGROUND /splash_portrait.bmp", see stm32mp-extlinux.bbappend),
# and it stays on screen until the kernel's real display driver takes over
# ~12 s after kernel start: the kernel first keeps U-Boot's framebuffer through
# its temporary "simpledrm" driver. The UI's own welcome screen then shows
# the same picture (ui_layer's app.slint), so the hand-over is seamless.
#
# The BMPs are generated by tools/welcome/make_welcome.py -- change the
# design there, not by editing the files. ST's recipe installs whatever
# UBOOT_SPLASH_*_SRC names under the fixed names splash_portrait.bmp /
# splash_landscape.bmp, so only the source file names change here; the
# DK2 (stm32mp15) uses the portrait one.
FILESEXTRAPATHS:prepend := "${THISDIR}/u-boot-stm32mp-splash:"

UBOOT_SPLASH_PORTRAIT_SRC = "welcome_480x800.bmp"
UBOOT_SPLASH_LANDSCAPE_SRC = "welcome_800x480.bmp"
