#!/usr/bin/env python3
"""
gen_oui.py -- builds backend_daemon's manufacturer table (issue #73).

The first three bytes of a MAC address (the "OUI") say which company made
the network chip or the device. The IEEE publishes the full list (~40000
companies, 4 MB). The hub only needs the ones that make smart-home things,
so this keeps a trimmed set and writes it as Rust source, compiled into
backend_daemon (src/oui_table.rs): ~25 KB instead of 4 MB, no file to read
at run time.

Run it again for each release to pick up new blocks:

    curl -o /tmp/oui.csv https://standards-oui.ieee.org/oui/oui.csv
    python3 tools/gen_oui.py /tmp/oui.csv \
        > linux_a7/backend_daemon/src/oui_table.rs

Only the large ("MA-L", 24-bit) blocks are used. Small companies that bought
a 28- or 36-bit block (mam.csv, oui36.csv) aren't in it -- most of them
use an Espressif or Realtek chip, whose MAC then says "Espressif".
"""
import csv
import re
import sys

# The name the hub shows -> what the IEEE's "Organization Name" looks like
# (a regular expression, case-insensitive). Order = the order in the table.
VENDORS = [
    # Chips inside most cheap WiFi devices (WLED, Tasmota, Tuya, Sonoff...).
    ("Espressif", r"espressif"),
    ("Realtek", r"realtek"),
    ("Beken", r"beken"),
    ("Bouffalo Lab", r"bouffalo"),
    # Smart-home brands.
    ("Tuya", r"tuya"),
    ("Sonoff", r"itead"),
    ("Shelly", r"allterco|shelly"),
    ("TP-Link", r"tp-link|tp link"),
    ("Xiaomi", r"xiaomi|lumi united|yeelink"),
    ("Roborock", r"roborock"),
    ("Dreame", r"dreame"),
    ("Ecovacs", r"ecovacs"),
    ("EZVIZ", r"ezviz"),
    ("Hikvision", r"hikvision"),
    ("Signify", r"signify|philips lighting|^wiz"),
    ("IKEA", r"ikea"),
    ("Broadlink", r"broadlink"),
    ("Meross", r"meross"),
    ("Nanoleaf", r"nanoleaf"),
    ("Netatmo", r"netatmo"),
    ("Bosch", r"bosch"),
    ("Arlo", r"arlo"),
    ("Ring", r"^ring llc"),
    ("Ubiquiti", r"ubiquiti"),
    ("Raspberry Pi", r"raspberry pi"),
    # TVs, speakers, streaming.
    ("LG Electronics", r"^lg electronics|lg innotek"),
    ("Samsung", r"samsung electronics"),
    ("Sony", r"^sony"),
    ("Panasonic", r"panasonic"),
    ("Hisense", r"hisense"),
    ("Philips TV", r"tp vision"),
    ("Sonos", r"sonos"),
    ("Amazon", r"amazon technologies"),
    ("Google", r"^google"),
    ("Roku", r"^roku"),
    ("Nintendo", r"nintendo"),
]


def main():
    rows = csv.DictReader(open(sys.argv[1], encoding="utf-8", errors="replace"))
    patterns = [(i, re.compile(p, re.I)) for i, (_, p) in enumerate(VENDORS)]
    table = {}
    for row in rows:
        if row["Registry"] != "MA-L":
            continue
        name = row["Organization Name"]
        for i, pattern in patterns:
            if pattern.search(name):
                table[int(row["Assignment"], 16)] = i
                break

    out = sys.stdout
    out.write("/*\n")
    out.write(" * oui_table.rs -- GENERATED by tools/gen_oui.py from the IEEE OUI list\n")
    out.write(" * (issue #73). Don't edit by hand: run the script again (see its header).\n")
    out.write(" *\n")
    out.write(" * VENDORS: the names shown. OUI: (first three bytes of a MAC, index into\n")
    out.write(" * VENDORS), sorted by the bytes so oui.rs can binary-search it.\n")
    out.write(" */\n")
    out.write("pub const VENDORS: &[&str] = &[\n")
    for name, _ in VENDORS:
        out.write(f'    "{name}",\n')
    out.write("];\n\n")
    out.write(f"pub const OUI: &[(u32, u8); {len(table)}] = &[\n")
    items = sorted(table.items())
    for start in range(0, len(items), 6):
        chunk = items[start:start + 6]
        out.write("    " + " ".join(f"(0x{k:06x}, {v})," for k, v in chunk) + "\n")
    out.write("];\n")
    print(f"gen_oui: {len(table)} blocks, {len(VENDORS)} vendors", file=sys.stderr)


if __name__ == "__main__":
    main()
